# Generated by Django 5.2.1 on 2025-06-26 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistente',
            name='puntos_asistencia',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='asistente',
            name='puntos_comida',
            field=models.IntegerField(default=0),
        ),
    ]
